import { AxiosResponse } from 'axios'
import { GetTreasuresResponse } from '../../api/codegen/data-contracts'

const mockAxiosResponse: AxiosResponse<GetTreasuresResponse> = {
  data: {
    list: [
      {
        betRequirement: '0.4',
        createdAt: '2024-03-14T10:00:00Z',
        directSubBetRequirement: '0.2',
        id: 1,
        remainingClaimAmount: '75.00',
        remainingUnlockAmount: '50.00',
        rewardAmount: '150.00',
        rewardType: 'USDT',
        status: 'UNLOCKING',
      },
      {
        betRequirement: '0.5',
        createdAt: '2024-03-14T11:00:00Z',
        directSubBetRequirement: '0.3',
        id: 6,
        remainingClaimAmount: '125.00',
        remainingUnlockAmount: '100.00',
        rewardAmount: '250.00',
        rewardType: 'TON',
        status: 'UNLOCKING',
      },
      {
        betRequirement: '0.6',
        createdAt: '2024-03-15T11:00:00Z',
        directSubBetRequirement: '0.4',
        id: 2,
        remainingClaimAmount: '200.00',
        remainingUnlockAmount: '200.00',
        rewardAmount: '200.00',
        rewardType: 'TON',
        status: 'STANDBY',
      },
      {
        betRequirement: '0.3',
        createdAt: '2024-03-13T10:00:00Z',
        directSubBetRequirement: '0.1',
        id: 3,
        remainingClaimAmount: '0.00',
        remainingUnlockAmount: '0.00',
        rewardAmount: '180.00',
        rewardType: 'KATON',
        status: 'UNLOCKED',
      },
      {
        betRequirement: '0.7',
        createdAt: '2024-03-15T12:00:00Z',
        directSubBetRequirement: '0.5',
        id: 4,
        remainingClaimAmount: '300.00',
        remainingUnlockAmount: '300.00',
        rewardAmount: '300.00',
        rewardType: 'KATON',
        status: 'STANDBY',
      },
      {
        betRequirement: '0.4',
        createdAt: '2024-03-13T11:00:00Z',
        directSubBetRequirement: '0.2',
        id: 5,
        remainingClaimAmount: '100.00',
        remainingUnlockAmount: '100.00',
        rewardAmount: '220.00',
        rewardType: 'USDT',
        status: 'UNLOCKED',
      },
      {
        betRequirement: '0.5',
        createdAt: '2024-03-15T10:00:00Z',
        directSubBetRequirement: '0.3',
        id: 7,
        remainingClaimAmount: '100.00',
        remainingUnlockAmount: '100.00',
        rewardAmount: '100.00',
        rewardType: 'USDT',
        status: 'STANDBY',
      },
      // 新增的 UNLOCKING 數據
      ...Array.from({ length: 18 }, (_, index) => ({
        betRequirement: (0.3 + Math.random() * 0.5).toFixed(1),
        createdAt: new Date(2024, 2, 14 + index, 10 + (index % 14), 0, 0).toISOString(),
        directSubBetRequirement: (0.3 + Math.random() * 0.5).toFixed(1),
        id: 8 + index,
        remainingClaimAmount: (0.3 + Math.random() * 0.5).toFixed(1),
        remainingUnlockAmount: (0.3 + Math.random() * 0.5).toFixed(1),
        rewardAmount: (0.3 + Math.random() * 0.5).toFixed(1),
        rewardType: 'USDT' as 'USDT' | 'TON' | 'KATON',
        status: 'UNLOCKED' as 'STANDBY' | 'UNLOCKING' | 'UNLOCKED',
      })),
    ],
  },
  status: 200,
  statusText: 'OK',
  headers: {
    'Content-Type': 'application/json',
  },
  config: {},
}

export default mockAxiosResponse
