export { default as BtcIcon } from './btc'
export { default as CatAvatarIcon } from './cat-avatar'
export { default as CheckIcon } from './check'
export { default as EnergyIcon } from './energy'
// export { default as EnterByFloatingIcon } from './enter-by-floating'
export { default as GlobalIcon } from './global'
export { default as KatonIcon } from './katon'
export { default as SmashEggIcon } from './smash-egg'
export { default as StarIcon } from './star'
export { default as TonIcon } from './ton'
export { default as TreasureIcon } from './treasure'
export { default as TreasureRandomIcon } from './treasure-random'
export { default as TwitterIcon } from './twitter'
export { default as UsdtIcon } from './usdt'
export { default as WaitingIcon } from './waiting'
export { default as ClockIcon } from './clock'
